version: '3.7'
  
secrets:
  keystore:
    external: true

services:
  core:
    image: "sebohe/rinkeby-geth"
    deploy:
      mode: global
    secrets:
      - keystore
    volumes:
      - type: bind
        source: /mnt/blockchain_ipfs/geth
        target: /blockchain
    ports:
      - "9545:9545"
    entrypoint:
      - geth
      - --rinkeby
      - --cache
      - "10000"
      - --rpc
      - --rpcport
      - "9545"
      - --rpcaddr
      - 0.0.0.0
      - --rpcvhosts
      - http://sasquatch.network
      - --datadir
      - /blockchain
      - --keystore
      - /keystore
      - --syncmode
      - fast
      - --unlock
      - "0"
      - --password
      - /run/secrets/keystore
