version: '3.7'
  
volumes:
  geth-blockchain:

secrets:
  keystore:
    external: true

services:
  core:
    image: "ethereum/client-go:stable"
    deploy:
      mode: global
    entrypoint:
      - /usr/local/bingeth
      - --rinkeby
      - --rpc
      - --rpcvalue 0.0.0.0.
      - --rpcport 9545
      - --rpcapi all
      - --datadir "/blockchain"
      - --keystore "/run/secrets/keystore"
    secrets:
      - keystore
    volumes:
      - "geth-blockchain:/blockchain"
    ports:
      - "9545:9545"
