version: '3.7'

services:
  ipfs:
    image: "ipfs/go-ipfs"
    deploy:
      mode: global
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./ipfs-docker-entrypoint.sh:/entrypoint.sh:ro
      - /mnt/blockchain_ipfs/ipfs/staging:/export
      - /mnt/blockchain_ipfs/ipfs/data/data/ipfs
