version: '3.7'
  
secrets:
  keystore:
    external: true

services:
  core:
    image: "ethereum/client-go:stable"
    deploy:
      mode: global
    volumes:
      - /mnt/blockchain_ipfs/geth:/blockchain
    ports:
      - "9545:9545"
      - "9546:9546"
    entrypoint:
      - geth
      - --cache
      - "8192"
      - --rpc
      - --rpcport
      - "9545"
      - --rpcaddr
      - 0.0.0.0
      - --rpcapi
      - "debug,eth,net,web3"
      - --rpcvhosts
      - "*"
      - --rpccorsdomain
      - "http://sasquatch.network,https://sasquatch.network"
      - --ws
      - --wsaddr
      - 0.0.0.0
      - --wsport
      - "9546"
      - --wsorigins
      - "*"
      - --datadir
      - /blockchain
      - --syncmode
      - fast
      - --v5disc
      - --vmdebug
version: '3.7'
  
secrets:
  keystore:
    external: true

services:
  core:
    image: "parity/parity:beta"
    deploy:
      mode: global
    secrets:
      - keystore
    volumes:
      - ./keystore.json:/keystore/keystore.json:ro
      - ./password:/password:ro
      - /mnt/blockchain_ipfs/parity:/blockchain
    ports:
      - "10545:9545"
      - "10546:9546"
    entrypoint:
      - parity 
      - --chain
      - kovan
      - --cache-size
      - "8192"
      - --jsonrpc-port
      - "9545"
      - --jsonrpc-interface
      - 0.0.0.0
      - --jsonrpc-apis
      - "debug,eth,net,web3,shh,personal"
      - --jsonrpc-cors
      - "http://sasquatch.network,https://sasquatch.network"
      - --base-path
      - /parity
      - --db-path
      - /blockchain
