version: '3.7'

services:
  mainnet:
    image: "parity/parity:stable"
    deploy:
      mode: global
    volumes:
      - ~/blockchain:/blockchain
    ports:
      - "39545:9545"
      - "39546:9546"
    entrypoint:
      - parity
      - --jsonrpc-port=9545
      - --jsonrpc-interface=all
      - --jsonrpc-hosts=all
      - --jsonrpc-apis=safe
      - --jsonrpc-cors=all
      - --ws-port=9546
      - --ws-interface=all
      - --ws-apis=safe
      - --ws-origins=all
      - --ws-hosts=all
      - --auto-update=all
      - --cache-size=4096
      - --no-secretstore
      - --no-hardware-wallets
      - --no-ipc
      - --db-path=/blockchain
