version: '3.7'
  
secrets:
  keystore:
    external: true

services:
  core:
    image: "parity/parity:beta"
    deploy:
      mode: global
    secrets:
      - keystore
    volumes:
      - ./keystore.json:/keystore/keystore.json:ro
      - ./password:/password:ro
      - /mnt/blockchain_ipfs/parity:/blockchain
    ports:
      - "10545:9545"
      - "10546:9546"
    entrypoint:
      - parity 
      - --chain
      - kovan
      - --cache-size
      - "8192"
      - --jsonrpc-port
      - "9545"
      - --jsonrpc-interface
      - 0.0.0.0
      - --jsonrpc-apis
      - "debug,eth,net,web3,shh,personal"
      - --jsonrpc-cors
      - "http://sasquatch.network,https://sasquatch.network"
      - --base-path
      - /parity
      - --db-path
      - /blockchain
      - --keys-path
      - /keystore
