version: '3.7'
  
volumes:
  blockchain:

secrets:
  keystore:
    external: true

services:
  core:
    image: "parity/parity:stable"
    deploy:
      mode: global
    entrypoint:
      - /parity/parity
      - --base-path=/blockchain
      - --chain=kovan
      - --no-ui
      - --jsonrpc-port=27148
      - --jsonrpc-interface=0.0.0.0 
      - --jsonrpc-apis=all
    secrets:
      - keystore
    volumes:
      - "blockchain:/blockchain"
    ports:
      - "27148:27148"
