version: '3.7'
  
services:
  rinkeby:
    image: "ethereum/client-go:stable"
    deploy:
      mode: global
    volumes:
      - /mnt/blockchain_ipfs/aragon:/blockchain
    ports:
      - "19545:9545"
      - "19546:9546"
    entrypoint:
      - geth
      - --rinkeby
      - --cache
      - "8192"
      - --rpc
      - --rpcport
      - "9545"
      - --rpcaddr
      - 0.0.0.0
      - --rpcapi
      - "debug,eth,net,txpool,web3"
      - --rpcvhosts
      - "*"
      - --rpccorsdomain
      - "http://sasquatch.network,https://sasquatch.network"
      - --ws
      - --wsaddr
      - 0.0.0.0
      - --wsport
      - "9546"
      - --wsorigins
      - "ws://sasquatch.network,*"
      - --wsapi
      - "debug,eth,net,txpool,web3"
      - --datadir
      - /blockchain
      - --syncmode
      - fast
      - --v5disc
