version: '3.7'

services:
  core:
    image: "ipfs/go-ipfs:v0.4.18"
    deploy: 
      mode: global
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
      - "8080:8080"
    volumes:
      - ~/ipfs/data:/data/ipfs
      - ~/ipfs/staging:/export
