global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 5s
scrape_configs:
- job_name: goerli
  metrics_path: /debug/metrics/prometheus
  scheme: http
  static_configs:
  - targets:
    - goerli:6060
- job_name: rinkeby
  metrics_path: /debug/metrics/prometheus
  scheme: http
  static_configs:
  - targets:
    - rinkeby:6060
